"""Init table

Revision ID: 82c708da4410
Revises: 
Create Date: 2023-06-28 14:23:15.884354

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "82c708da4410"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("to_send", sa.String(length=256), nullable=True),
        sa.Column("sent", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mails")
    # ### end Alembic commands ###
